// This file is automatically generated from your CSS. Any edits will be overwritten.
export const loading: string;
export const spin: string;
export const hide: string;
export const shown: string;
export const fadeIn: string;
